### ISSUE TITLE
.#production not loaded

### ISSUE THREAD

**Issue by rpersaud** [matb33/meteor-ec2-install#10]
I add the .#production to my local meteor root directory, then git push ec2 master to have it loaded after I follow all the instructions here. When I run node main.js, I get MONGO_URL must be set in environment. My ubuntu parent directory on the Amazon EC2 has all my .#production loaded into the .<servicename> hidden file, with /usr/bin/node /home/ubuntu/splassh/main.js >> $1 2>&1 appended to the very end. I'm thoroughly confused on what is the proper way to load config/environment variables like MONGO_URL, MAIL_URL, FACEBOOK_APP_ID, etc using the .#production. I initially built my meteor app using settings.json and loading it w/ Meteor --settings, but I doubt this will work natively with this install script. Any ideas on what is happening? Thanks,

**Comment by matb33** [comment]
Does your Meteor app load at all, i.e. does node end up running?

**Comment by rpersaud** [comment]
Deploying via PORT=80 MONGO_URL=... ROOT_URL=... nohup node main.js & 

does show some console errors re: client side code I had written, which works locally running with >meteor.

I also noticed my exports within .#production contained a few spaces between the assignments.

And of course, meteor has been updated to 0.6.5, so I'm currently testing it out locally with the update.

**Comment by rpersaud** [comment]
I finally got my meteor app to work on my t1.micro Amazon ec2 by following this install file, then sourcing the $APPEXECUTABLE to no avail, re-installing fibers since meteor 0.6.5 changes where node_modules are stored, and then deploying from the command line with all my environment variables manually typed out.

cd ~/
source .myproject
cd myproject/programs/server/node_modules
rm -rf fibers
sudo npm install fibers@1.0.1
cd ~/myproject
sudo service myproject stop
sudo PORT=80 MONGO_URL=... MAIL_URL=... ROOT_URL... FACEBOOK_APP_ID=... nohup node main.js &

and then it worked ... the install.sh will need to be updated to fix fibers. 

Even after sourcing the .myproject file, the variables were present when I echo $MONGO_URL, but I guess meteor requires that you explicitly load this.

**Comment by matb33** [comment]
I wonder if it's as simple as updating the script to install fibers 1.0.1 instead of 1.0.0... I'll push an update shortly with this change
