### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by littke** [matb33/meteor-ec2-install#6]
I seem to be unable to get my submodules along when deploying, so the less compiler is complaining that a mixin (defined in a submodule and put the packages dir) isn't found, hence the bundling fails.

I've read about git-archive-all and will try to use it. Not sure that's the way to go or that this is even the problem, just wanted to let you know.

Thanks so much for this script!

**Comment by littke** [comment]
I ended up following the advice of this SO-thread: http://stackoverflow.com/questions/5482544/how-can-i-use-git-archive-to-include-submodules-from-a-bare-repository

.. and git archive-all.

**Comment by matb33** [comment]
So does that mean that if we change this line:

```
git archive master | tar -x -C $EXPORTFOLDER
```

to

```
git archive-all master | tar -x -C $EXPORTFOLDER
```

then submodules are supported? I looked through the SO link quickly and it appeared to be trickier. I'll re-read though

**Comment by littke** [comment]
Not that simple. I cloned the repo, cd'ed into it, ran `git submodule update --init --recursive`, and ran `git archive-all` on THAT. Didn't see a place to specify a branch, either, so I manually checked it out. Also, `git archive-all` wants an `OUTPUT_FILE` rather than just returning it, so I couldn't pipe.

Lastly, redownloading all packages on each deploy seems slow, I'm sure it can be improved. But since I'm right now deleting /tmp/${SERVICE} each time, that's what happens.

**Comment by matb33** [comment]
This deserves some attention. I'll get around to it at some point, but welcome any pull requests. I'm not personally using any submodules for my current project. If I do, this will get immediate attention ;-)

**Comment by littke** [comment]
You should! :)

Everything you include as a package should be a submodule. ^_^

**Comment by matb33** [comment]
Good point, although my app consists of ONLY packages btw =) `public/` and `packages/` is all I've got in my root

But I get what you mean, any package that is of the re-usable form would def benefit from being a submodule... Going to think on that

**Comment by littke** [comment]
Yeah. It makes it easier to get upgrades from `upstream`, making sure you're not out of sync. Extra important given how fast we're moving with Meteor. Using submodules this way, you can decide on your own when you want to upgrade: your superproject is always pointing to a certain commit, so no autoupdating will be done.

**Comment by matb33** [comment]
9 months later, submodule support is in
