### ISSUE TITLE
adding support for meteorite

### ISSUE THREAD

**Issue by rpersaud** [matb33/meteor-ec2-install#8]
I noticed my meteorite packages weren't being bundled, so this is how I'm supporting it using this script and an ubuntu 64 12.04 lts ec2 free tier:

Add this function:

function install_meteorite {
        echo "--------------------------------------------------------------------------------"
        echo "Install Meteorite"
        echo "--------------------------------------------------------------------------------"

```
    sudo -H npm install meteorite -g
```

}

then append to the post-receive hook right after "meteor update"

   append $HOOK "mrt install"

then call install_meteorite at end.

**Comment by matb33** [comment]
Excellent. I'll think about how to add this... maybe conditionally, or just something you comment-out

**Comment by matb33** [comment]
This has been added in version 1.0.1
